---
deployment:
  tasks:
  - export DEPLOYPATH=/home/n9501w8w25y5/public_html
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp theodore.css $DEPLOYPATH 
  - /bin/cp thankyou.html $DEPLOYPATH
  - /bin/cp script.js $DEPLOYPATH
  - /bin/cp theodore.sass $DEPLOYPATH
  - /bin/cp -R /fonts/* $DEPLOYPATH
  - /bin/cp -R /images/* $DEPLOYPATH